name: CI Tarefas CRUD

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Executar Testes Unitários
      run: python3 -m unittest test_tarefas.py